In [3]:
def my_function(x, y):
    pass

In [4]:
def my_sq(x):
    return x ** 2

In [5]:
my_sq(2)

4

In [6]:
my_sq(4)

16

In [11]:
assert my_sq(4) == 16

In [12]:
def avg_2(x, y):
    return (x + y) / 2

In [13]:
avg_2(10, 20)

15.0

In [18]:
import pandas as pd

In [19]:
df = pd.DataFrame({
    'a': [10, 20, 30],
    'b': [20, 30, 40]
})

In [20]:
df

a   b
0  10  20
1  20  30
2  30  40

In [22]:
df['a'] ** 2

0    100
1    400
2    900
Name: a, dtype: int64

In [23]:
my_sq

<function __main__.my_sq(x)>

In [24]:
df['a'].apply(my_sq)

0    100
1    400
2    900
Name: a, dtype: int64

In [25]:
def my_exp(x, e):
    return x ** e

In [26]:
my_exp(2, 10)

1024

In [27]:
df['a'].apply(my_exp, e=4)

0     10000
1    160000
2    810000
Name: a, dtype: int64

In [28]:
def print_me(x):
    print(x)

In [29]:
df.apply(print_me)

0    10
1    20
2    30
Name: a, dtype: int64
0    20
1    30
2    40
Name: b, dtype: int64


a    None
b    None
dtype: object

In [32]:
df

a   b
0  10  20
1  20  30
2  30  40

In [30]:
def avg_3(x, y, z):
    return (x + y + z) / 3

In [31]:
df.apply(avg_3)

TypeError: ("avg_3() missing 2 required positional arguments: 'y' and 'z'", 'occurred at index a')

In [33]:
import numpy as np

In [34]:
def avg_3_apply(col):
    return np.mean(col)

In [35]:
df.apply(avg_3_apply)

a    20.0
b    30.0
dtype: float64

In [40]:
df

a   b
0  10  20
1  20  30
2  30  40

In [37]:
def avg_3_apply(col):
    x = col[0]
    y = col[1]
    z = col[2]
    return (x + y + z) / 3

In [38]:
df.apply(avg_3_apply)

a    20.0
b    30.0
dtype: float64

In [39]:
df.apply(avg_3_apply, axis='columns')

IndexError: ('index out of bounds', 'occurred at index 0')

In [41]:
df['a'].mean()

20.0

In [42]:
df['a'] + df['b']

0    30
1    50
2    70
dtype: int64

In [45]:
def avg_2_mod(x, y):
    if (x == 20):
        return np.NaN #np.NAN np.nan
    else:
        return(x + y) / 2

In [46]:
df

a   b
0  10  20
1  20  30
2  30  40

In [47]:
avg_2_mod(df['a'], df['b'])

ValueError: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().

In [48]:
import numpy as np

In [49]:
avg_2_mod_vec = np.vectorize(avg_2_mod)

In [51]:
df

a   b
0  10  20
1  20  30
2  30  40

In [50]:
avg_2_mod_vec(df['a'], df['b'])

array([15., nan, 35.])

In [53]:
@np.vectorize
def avg_2_mod(x, y):
    if (x == 20):
        return np.NaN #np.NAN np.nan
    else:
        return(x + y) / 2

In [54]:
avg_2_mod(df['a'], df['b'])

array([15., nan, 35.])

In [55]:
import numba

In [59]:
@numba.vectorize
def avg_2_mod_numba(x, y):
    if (x == 20):
        return np.NaN
    else:
        return(x + y) / 2

In [60]:
avg_2_mod_numba(df['a'].values, df['b'].values)

array([15., nan, 35.])

In [62]:
%%timeit
avg_2(df['a'], df['b'])

445 µs ± 7.79 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [63]:
%%timeit
avg_2_mod(df['a'], df['b'])

211 µs ± 7.73 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [64]:
%%timeit
avg_2_mod_numba(df['a'].values, df['b'].values)

8.01 µs ± 226 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
